tor:
  protocol: socks5
  port: 9050
  control_port: 9051
  password: ~

proxies: ~

proxy:
  address: user:password@host:port
  protocol: http

# or, if there is not password
# proxy:
#   address: host:port
#   protocol: http
# the protocol can be Null